packages:
  - "packages/*"
  - "apps/*"
  - "!apps/example"
catalog:
  "@algolia/autocomplete-core": 1.19.4
  "@changesets/cli": ^2.29.8
  "@inquirer/core": 10.3.2
  "@clack/prompts": 0.11.0
  boxen: 8.0.1
  commander: 14.0.2
  inquirer: 12.11.1
  chalk: 5.6.2
  cli-table3: 0.6.5
  ora: 8.2.0
  yaml: 2.8.2
  fs-extra: 11.3.3
  fast-glob: ^3.3.3
  flexsearch: 0.8.212
  framer-motion: 12.23.26
  glob: 11.1.0
  semver: 7.7.3
  gray-matter: ^4.0.3
  husky: ^9.1.7
  lint-staged: ^16.2.7
  mdast-util-to-string: ^4.0.0
  mdx-annotations: ^0.1.4
  "@headlessui/react": 2.2.9
  "@mdx-js/loader": 3.1.1
  "@mdx-js/react": 3.1.1
  "@next/mdx": 15.5.9
  npm-registry-fetch: 18.0.2
  pacote: 21.0.4
  lodash: ^4.17.21
  msw: ^2.12.4
  next-intl: 4.6.1
  next-mdx-remote: ^5.0.0
  next-themes: ^0.4.6
  prettier-plugin-organize-imports: 4.3.0
  react-highlight-words: ^0.21.0
  react-icons: ^5.5.0
  remark: ^15.0.1
  remark-gfm: ^4.0.1
  remark-mdx: 3.1.1
  rimraf: ^6.1.2
  rxjs: 7.8.2
  shiki: ^0.14.7
  simple-functional-loader: ^1.2.1
  "@sindresorhus/slugify": ^2.2.1
  "@tailwindcss/postcss": 4.1.18
  "@tailwindcss/typography": 0.5.19
  tsx: ^4.21.0
  turbo: 2.7.2
  typescript: 5.8.3
  "@types/mdx": ^2.0.13
  zod: 3.25.76
  tsup: 8.5.1
  vitest: ^4.0.16
  "@types/react-highlight-words": 0.20.1
  acorn: ^8.15.0
  unist-util-filter: ^5.0.1
  unist-util-visit: ^5.0.0
  zustand: 5.0.9
  prettier: 3.7.4
  "@types/fs-extra": ^11.0.4
  "@types/inquirer": ^9.0.9
  "@types/lodash": ^4.17.21
  "@types/node": 25.0.3
  "@types/npm-registry-fetch": 8.0.9
  "@types/pacote": ^11.1.8
  "@types/semver": ^7.7.1
  "@vitest/coverage-v8": ^4.0.16
  "@vitest/ui": ^4.0.16
  # Frontend dependencies
  react: 19.2.3
  "react-dom": 19.2.3
  next: 15.5.9
  tailwindcss: 4.1.18
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3
  sharp: 0.34.5
  clsx: ^2.1.1
  "prettier-plugin-tailwindcss": 0.7.2
  vite: 5.4.21
  "@vitejs/plugin-react": 4.7.0
catalogs:
  node18:
    "@types/node": 25.0.3
  node20:
    "@types/node": 25.0.3
  node22:
    "@types/node": 25.0.3