packages:
  - packages/*
  - apps/*
  - "!apps/example"

catalog:
  "@algolia/autocomplete-core": ^1.19.2
  "@changesets/cli": ^2.29.8
  commander: 14.0.0
  inquirer: 12.7.0
  chalk: 5.4.1
  cli-table3: 0.6.5
  ora: 8.2.0
  yaml: 2.8.0
  fs-extra: 11.3.0
  fast-glob: ^3.3.3
  flexsearch: ^0.8.205
  framer-motion: ^12.23.11
  glob: 11.0.3
  semver: 7.7.2
  gray-matter: ^4.0.3
  husky: ^9.1.7
  lint-staged: ^16.2.7
  mdast-util-to-string: ^4.0.0
  mdx-annotations: ^0.1.4
  "@headlessui/react": ^2.2.6
  "@mdx-js/loader": ^3.1.0
  "@mdx-js/react": ^3.1.0
  "@next/mdx": ^15
  npm-registry-fetch: 18.0.2
  pacote: 21.0.0
  lodash: ^4.17.21
  msw: ^2.12.4
  next-intl: ^4.3.7
  next-mdx-remote: ^5.0.0
  next-themes: ^0.4.6
  prettier-plugin-organize-imports: ^4.2.0
  react-highlight-words: ^0.21.0
  react-icons: ^5.5.0
  remark: ^15.0.1
  remark-gfm: ^4.0.1
  remark-mdx: ^3.1.0
  rimraf: ^6.1.2
  rxjs: 7.8.2
  shiki: ^0.14.7
  simple-functional-loader: ^1.2.1
  "@sindresorhus/slugify": ^2.2.1
  "@tailwindcss/postcss": ^4.1.11
  "@tailwindcss/typography": ^0.5.16
  tsx: ^4.21.0
  turbo: ^2.6.3
  typescript: 5.8.3
  "@types/mdx": ^2.0.13
  zod: 3.25.75
  tsup: ^8.3.5
  vitest: ^4.0.16
  "@typescript-eslint/eslint-plugin": ^8.49.0
  "@typescript-eslint/parser": ^8.49.0
  "@types/react-highlight-words": ^0.20.0
  acorn: ^8.15.0
  unist-util-filter: ^5.0.1
  unist-util-visit: ^5.0.0
  zustand: ^5.0.6
  eslint: 9.30.1
  "@eslint/js": ^9.30.1
  prettier: 3.6.2
  "@types/fs-extra": ^11.0.4
  "@types/inquirer": ^9.0.9
  "@types/lodash": ^4.17.21
  "@types/node": ^25.0.1
  "@types/npm-registry-fetch": ^8.0.8
  "@types/pacote": ^11.1.8
  "@types/semver": ^7.7.1
  "@vitest/coverage-v8": ^4.0.16
  "@vitest/ui": ^4.0.16
  eslint-config-prettier: ^10.1.8
  eslint-plugin-import: ^2.32.0
  eslint-plugin-node: ^11.1.0
  eslint-plugin-prettier: ^5.5.4
  # Frontend dependencies
  react: ^19
  "react-dom": ^19
  next: ^15
  tailwindcss: ^4.1.11
  "@types/react": ^19
  "@types/react-dom": ^19
  "eslint-config-next": ^15
  sharp: 0.34.3
  clsx: ^2.1.1
  "prettier-plugin-tailwindcss": ^0.6.14
  vite: ^5.4.11
  "@vitejs/plugin-react": ^4.3.4

catalogs:
  node18:
    "@types/node": 18.19.59
  node20:
    "@types/node": 20.19.17
  node22:
    "@types/node": 22.9.4
